build-prod:
	docker build -t mveyone/todo2-mern-client-prod .
	docker push mveyone/todo2-mern-client-prod

build-dev:
	docker build -t mveyone/todo2-mern-api-dev .
	docker push mveyone/todo2-mern-api-dev